server:
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-a  # 路由id，自定义，只要唯一即可
#          uri: lb://service-a  # 路由的目标地址，lb就是负载均衡，后面跟着的是服务名称
          uri: http://localhost:8081  # 路由的目标地址，lb就是负载均衡，后面跟着的是服务名称
          predicates:
            - Path=/api/**  # 按照这个路径进行匹配，只要以/user/开头就符合要求
          filters:
            - StripPrefix=1  # 用于去掉路径中的第一个前缀，这样 /api/user 会被转发为 /user
      globalcors:  # 解决跨域问题
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://example.com"  # 允许的域名
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true  # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期